### ISSUE TITLE
Color Change

### ISSUE THREAD

**Issue by grahamchallen** [tom-2015/rpi-ws2812-server#12]
Hi, looking for some insight into the color change, using the SK6812 IC LED strip.

Using the code to simply turn on all of the LEDS to a red color.

I turn on all of the lights however LED 1,2,3 and 4 turn red, blue, white and green ? 

Is this a default config with the LED strip ?

**Comment by tom-2015** [comment]
Did you configure the software for the SK8912 with the setup command?
Did you turn off the on board analog audio driver? This uses the PWM output and messes up the timings.

**Comment by grahamchallen** [comment]
Easy Fix, thank you
