### ISSUE TITLE
Run terminal code on startup

### ISSUE THREAD

**Issue by grahamchallen** [tom-2015/rpi-ws2812-server#13]
Looking to have the restart each day, is there a place which I can put the:

cd rpi-ws2812-server
sudo ./ws2812svr -tcp 1111

to make it run on startup in terminal?

**Comment by tom-2015** [comment]
Yes, search google on 'raspberry run program at startup' you'll find many ways to do this.
One way is to create a script file in the rpi-ws2812-server directory (for example run.sh) this script will start the server.

`nano run.sh`

type text:

```
#!/bin/bash
cd /home/pi/rpi-ws2812-server
sudo ./ws2812svr -tcp 1111
```
CTRL+X to exit and save changes.

to make the script executable:

`sudo chmod 777 run.sh`

Then type crontab -e and add text:
`@reboot /home/pi/rpi-ws2812-server/run.sh`
