### ISSUE TITLE
Flashing Command

### ISSUE THREAD

**Issue by grahamchallen** [tom-2015/rpi-ws2812-server#15]
Is it possible to make a flashing command to run for a specific amount of time?

**Comment by tom-2015** [comment]
If you are not running the program using a text file or TCP socket you can use a loop.
For example flash 10 times with a 250ms ON / OFF.

do
   fill  1, FFFFFF
   render
   delay 250
   fill 1, 000000
   render
   delay 250
loop 10

**Comment by tom-2015** [comment]
Blink command is now added for making some LEDs flash between 2 colors.
