### ISSUE TITLE
Send fade command to tcp

### ISSUE THREAD

**Issue by Oakley1212** [tom-2015/rpi-ws2812-server#16]
Hi Tom,

I got a problem sending a simple fade command to the tcp socket.
I wanna send fade 1,200,100,10,1 to the tcp socket Server working on port 9999.
But it seems that the command gets ignored.

From the command line it is working flawless.
I also came across the issue that when using "setup 1,xxx;init;fade ...." on the command line it is not working.
But using setup 1,xxx -> enter -> init -> enter and then fade .... fading works as it should.

This is the main part of my php file sending the command to the leds.
setup 1,xxx;init; has been called and already sent earlier.

if ($cmd!=''){
    switch ($cmd){
        case 'fill':
            $data = "fill 1,$color;render;";
            break;
	case 'rainbow':
            $data = "rainbow;render;";
            break;	
        case 'fade':
            $data = "fade 1,200,100,10,1";  //<- omitted render because "fade" is working without in command line
            break;
        case 'bright':
            $data = "brightness 1,$bness;render;";			
            break;
    }
    send_to_leds($data);
}

function send_to_leds ($data){
    $sock = fsockopen($serverip, 9999);
    fwrite($sock, $data);
    fclose($sock);
}

Best regards...

Mirko

**Comment by tom-2015** [comment]
Hi

Can you try adding a ; or ENTER after the fade command like:

$data = "fade 1,200,100,10,1**;**";

Probably the program is waiting for this to complete the command.

Sorry for the slow reply I was on vacation.
