### ISSUE TITLE
Pass setup parameters on server start?

### ISSUE THREAD

**Issue by alphapapa77** [tom-2015/rpi-ws2812-server#17]
Any way to pass setup parameters on start?

Like:
`sudo ./ws2812svr -s 1,50 -tcp 9999`

Or is there a way to find out if the server has already been initialized?

**Comment by tom-2015** [comment]
not yet but can be added I think

**Comment by tom-2015** [comment]
This is now possible with -i command option.

sudo ./ws2812svr -i "setup 1,4,5;init;"

**Comment by alphapapa77** [comment]
This is great news - thank you for creating this awesome program


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
10/01/18,
7:33:29 PM
