### ISSUE TITLE
Issue when compiling without PNG and JPEG

### ISSUE THREAD

**Issue by maxiimilian** [tom-2015/rpi-ws2812-server#18]
There is a problem with the Makefile. In line 4 the png and jpg libraries are added to the linker (at least I assume that is what happens) without checking if PNG or JPG is required. Ultimately, this results in a compiler error if the libraries are not installed.

I fixed it by first removing `-lpng` and `-ljpeg` from `LINK=` in line 4. Afterwards, I modified the top of the Makefile to look like this:

    ifneq (1,$(NO_PNG))
        CC += -DUSE_PNG
        LINK += -lpng
    endif

    ifneq (1,$(NO_JPEG))
        CC += -DUSE_JPEG
        LINK += -ljpeg
    endif

Since I don't really know how to start a pull request I figured I would open this issue to let you know. Also, I am not quite sure if the fix is 100% correct.

**Comment by tom-2015** [comment]
Ok I'll update the code.
Thanks for letting me know.
