### ISSUE TITLE
Update Color of a Single Pixel

### ISSUE THREAD

**Issue by bwlange3** [tom-2015/rpi-ws2812-server#19]
First, I would like say thank you for a great project.  This has been very helpful and works perfectly.  I am having a great time testing its capabilities.

I am trying to discover a way update the color of a single pixel without effecting the color or re-rendering the rest of the pixels.  Is that possible?  The reason I am trying to do this is to create some "effects" like a color wipe and some others.  I have successfully developed a color wipe script using the rotate command but I get a flash because its necessary to first render the previous color before I start the rotate.  Also if the previous color of the leds happen to be in a rainbow that does not work because it rotates as well.  Code below is part of my php contoller page (hence the php variables):

```
fill 1,$prevColor;
thread_start;
do;
rotate 1,1,0,$color;
brightness 1,$brightness;
render;
delay $speed;
loop $ledQty;
thread_stop;
```

Sorry for many questions but I have a few more...

I am also having trouble with the gradient command.  I would like to create a gradient that goes from (for example) FFFFFF to FF0000 and spans 50 pixels.  Using the supplied gradient command, how would I accomplish that?

Could you explain the <OR,AND,XOR,NOT,=> operators for the fill command and an example of how one might use them?

Also, did anyone ever get the fade command to work over TCP?

Thanks in advance for the reply!

**Comment by tom-2015** [comment]
To update a single pixel without affecting the rest you can use the fill command with start and len parameters.

fill 1,FF0000,5,1 #this will change the color of led 6 to FF0000

For the gradient try this:
fill 1,FFFFFF,0,50; #fill first 50 leds of channel 1 with white color or FFFFFF
gradient 1,G,255,0,0,50; #make the green component go from FF hex (255 dec) to 0  over 50 keds starting at 0
gradient 1,B,255,0,0,50; #make the blue component go from FF to 0 over 50 leds starting at 0
render; #now render

The binary operators OR,AND,XOR,NOT to use on current color and new color. For example if all leds have current color FF0000 this command will change the color to FF00FF:
fill 1,FF00FF,0,50,OR
This will change to (FF0000 XOR FF00FF) = 0000FF:
fill 1,FF00FF,0,50,XOR
You can use the Windows calculator in programming + hex mode to calculate the result. This can be useful if you load a PNG/JPG file and want to print a cursor or pointer over the image without knowing the actual pixel values.

I don't know about the fade command I'll have to try but normally it should work over TCP.

**Comment by bwlange3** [comment]
Thanks for the prompt reply!

Unfortunately I can't seem to update a single pixel without effecting the others.  When I try a simple fill command (fill 1,FF0000,5,1;) just clears or turns off all led's.  If I add render to the end (fill 1,FF0000,5,1;render;) it will render the single pixel as red but it clears or turns off all other led's.

Thanks for the assistance with the gradient command - that helps a lot!

Also I am unable to get fade (fade 1,255,5,20;) to work over TCP.  Instead it just shuts off all led's with no fade.

**Comment by tom-2015** [comment]
What if you do:
fill 1,FFFFFF;
fill 1,FF0000,5,1;
render;

I'll check the fade command this weekend.

**Comment by bwlange3** [comment]
Again, thanks for the prompt reply.

That solution worked but I have also discovered the actual issue I was having which actually corrected the fade problem.  I was sending the setup and init commands each time my PHP page was called for a change which would reset the LED's to blank each time.  I removed that and now everything is functioning perfectly.  Thanks again for help and the great project!
