### ISSUE TITLE
Run as System Service

### ISSUE THREAD

**Issue by bwlange3** [tom-2015/rpi-ws2812-server#30]
Is there a way to run the server as a System Service on the Raspberry Pi so that it runs all the time?

**Comment by tom-2015** [comment]
Not yet included but you can create a system service file yourself as described here:

[https://www.raspberrypi.org/documentation/linux/usage/systemd.md](url)

**Comment by maxiimilian** [comment]
I am a bit late but check my gist out: https://gist.github.com/maxiimilian/ac9666c5d1439d30b76bd82406e47613

I am running this service file on my Raspberry Pi 1 successfully.

**Comment by tom-2015** [comment]
Service is now included in the project with 
sudo make install

/etc/ws2812svr.conf 
here you can adjust the mode you want the service to run.
