### ISSUE TITLE
Cannot get a daemon to use port 9999

### ISSUE THREAD

**Issue by hans-martijn** [tom-2015/rpi-ws2812-server#44]
Hello,

my /etc/ws2812svr.conf is:

_#mode must be first setting in file!
mode=tcp
port=9999
file=/home/pi/test.txt
pipe=/dev/leds
init=setup 1,20,4,0,255,12;init_

if I start my server and I do a netstat -plnt I get any port above 35000, different every time. I probably have an error somewhere, but I cannot seem to find it. The server itself works, so that's not the problem.

Thanks in advance,
Hans

**Comment by Bigdeath** [comment]
Start it with root privileges.

**Comment by hans-martijn** [comment]
How else can I start a daemon?

**Comment by Bigdeath** [comment]
sudo

**Comment by hans-martijn** [comment]
I know, I wouldn't know how else to start a daemon...
![sudo](https://user-images.githubusercontent.com/59956528/81735160-eb2eb980-9494-11ea-918a-245efcb75e72.png)

**Comment by jQubz** [comment]
I think I fixed this in https://github.com/tom-2015/rpi-ws2812-server/pull/45

The daemon was always trying to listen on port 0 :)

**Comment by hans-martijn** [comment]
That works perfectly, thanks!!!
