### ISSUE TITLE
bash scripting question

### ISSUE THREAD

**Issue by oscarmh** [tom-2015/rpi-ws2812-server#50]
Hi, thanks for that server it is really amazing. Quick question, any suggestion to interact using bash scripting ? Thanks in advance

**Comment by tom-2015** [comment]
Start the server with the -p parameter or change the /etc/ws2812svr.conf file if you are using it as a daemon. This will create a named pipe you can write commands to.

sudo ./ws2812svr -p /dev/ws281x

in your script you can echo to the pipe:

echo "YOUR COMMAND;" > /dev/ws281x

**Comment by oscarmh** [comment]
Great !! Thanks a lot !!
