### ISSUE TITLE
Hardware revision is not supported

### ISSUE THREAD

**Issue by leoheck** [tom-2015/rpi-ws2812-server#53]
Hi @tom-2015 

I have one new different version of raspberry pi

This one

```
Hardware	: BCM2711
Revision	: b03112
Serial		: 100000002b336764
Model		: Raspberry Pi 4 Model B Rev 1.2
```

Please, check all the models here.

https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

**Comment by leoheck** [comment]
This one is Rpi 4, 2GB RAM

**Comment by tom-2015** [comment]
OK I'll add this version

**Comment by tom-2015** [comment]
New hardware was added now.

**Comment by leoheck** [comment]
It looks complete now, did you get this from here https://github.com/jgarff/rpi_ws281x ?
I realized later that jgarff had this file with the whole info.

**Comment by tom-2015** [comment]
Yes, I synced the code with the original from jgarff.
