### ISSUE TITLE
No donate button anywhere

### ISSUE THREAD

**Issue by fctr** [tom-2015/rpi-ws2812-server#56]
Do you have ANY IDEA how much time y'alls saved me by writing and releasing this? Is there a PayPal "donate" email address, or something like that, so I can show my appreciation?

**Comment by tom-2015** [comment]
Oh ok thanks, I've added paypal account to the sponsors section :)

**Comment by fctr** [comment]
Now all you need is a place for avid users to dump pictures, videos, and custom scripts of their projects!
