### ISSUE TITLE
Do .. loop on TCP

### ISSUE THREAD

**Issue by TheOriginal92** [tom-2015/rpi-ws2812-server#6]
Currently I'm having problems using a 

> do .. loop

 over TCP, all other commands work. My code is:

`  var String value = "
        setup 1,56,7;
        init;
        fill 1,FF000000,1,1;
        do;
              rotate;
              render;
              delay 100;
        loop;"`

With and without thread_start / stop it does not work.

I use OpenHAB with the TCP Binding to send the string.

**Comment by tom-2015** [comment]
You must use the tread_start and thread_stop commands and after sending your string you must close the TCP connection. After closing the TCP connection it should start the thread and run the loop.
