### ISSUE TITLE
Error set SO_KEEPALIVE

### ISSUE THREAD

**Issue by charlie-cheetah** [tom-2015/rpi-ws2812-server#7]
Hi,
I made a web page with a colorpicker that is sending a fill command to tcp socket immediately when color is changed. And I stumble upon this error, when I'm using the script:

Waiting for client to connect.
Error set SO_KEEPALIVE

The script is working fine for a while, and then this error occur. These two lines are displaying in a infinite loop. I think it may be because the script is sending new command too fast.

**Comment by tom-2015** [comment]
The error is generated in the PHP code?
What does the PHP script look like?

**Comment by charlie-cheetah** [comment]
It's a copy paste from example:

```
function send_to_leds ($data){  
   $sock = fsockopen("192.168.1.102", 9999);  
   fwrite($sock, $data);  
   fclose($sock);  
}
```

**Comment by tom-2015** [comment]
maybe the scrip is sending too much too fast, try adding usleep(10000); after the fwrite()

**Comment by tom-2015** [comment]
Should be fixed now
