### ISSUE TITLE
Hotspot feature to access webpage

### ISSUE THREAD

**Issue by Orm1server** [tom-2015/rpi-ws2812-server#9]
Hello,

First off new to GitHub,  my question and I think it in wrong place, but any chance you can include a hotspot that broadcasts the color picker webpage?  This rpi3 is going into my truck and won't have access to WiFi unless I specifically go out of way to set up hotspot.  Like I said prolly wrong area to ask but I'd still like to ask.

Thanks,
Steve

**Comment by tom-2015** [comment]
You can configure the hotspot manually.
This page explains how to set up a hotspot https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md

After that you should be able to access the color picker by entering the IP of you Raspberry in your browser.

**Comment by Orm1server** [comment]
Ok will try that thank you. Also awesome job at prompt responses

**Comment by Orm1server** [comment]
Found raspap to be best success
